name: Security Governance

on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches:
      - main
      - dev

jobs:
  mitigation-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR Git Diff
        run: |
          base_ref="${{ github.base_ref || 'main' }}"
          git fetch origin "$base_ref"
          git diff "origin/$base_ref...HEAD" > pr_changes.diff

      - name: Run Mitigation
        uses: mitigation-dot-team/action@main
        with:
          api-key: ${{ secrets.MITIGATION_API_KEY  }}
          diff-file: pr_changes.diff
        env:
          TOKEN: ${{ secrets.TOKEN }}
